config/routes.rb
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'User', at: 'auth'
  root to: 'jobs#index'

  devise_for :users, path: 'auth',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users

  resources :users do
    member do
      get :my_application
    end
  end

  resources :jobs do
    resources :job_applications do
      member do
        get :mark_as_seen
      end
    end
  end
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :job_applications

  def self.ransackable_attributes(_auth_object = nil)
    %w[title company created_at expires_at] # replace with the attributes you want to allowlist
  end
end

app/controllers/jobs_controller.rb
include Ransack::Helpers::FormHelper

class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /jobs or /jobs.json
  def index
    @q = params.dig(:q).present? ? Job.ransack(params[:q].merge!(expires_at_lteq: Time.now.to_date)) : Job.ransack({ expires_at_gteq: Time.now.to_date })
    @jobs = @q.result
  end

  # GET /jobs/1 or /jobs/1.json
  def show
    @job_applications = @job.job_applications
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.require(:job).permit(:id, :title, :description, :company, :location, :job_type,
                                :requirements, :published_at, :expires_at, :created_at, :updated_at)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with model: @job, local: true, class: "job-form" do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :company %>
    <%= form.text_field :company, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :job_type %>
    <%= form.select :job_type, options_for_select(["full-time", "part-time", "contract"]), { prompt: "Select job type" }, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :requirements %>
    <%= form.text_area :requirements, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :published_at %>
    <%= form.date_field :published_at, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= form.label :expires_at %>
    <%= form.date_field :expires_at, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to 'Back', jobs_path, class: "btn btn-secondary" %>
  </div>
  </div>
<% end %>

<style>
    .job-form {
        max-width: 600px;
        margin: 0 auto;
    }

    .form-group {
        margin-bottom: 1.5rem;
    }

    .form-label {
        font-weight: bold;
        font-size: 1.2rem;
        margin-bottom: 0.5rem;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: 0.5rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .form-control:focus {
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

</style>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<div class="form-title bg-primary text-white py-3">
  <h2>Jobs Board</h2>
</div>

<div class="wrapper wrapper-content animated ">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="container-fluid">
          <div class="row">
            <div class="col-4 p-3">
              <% if can?(:create, @job) %>
                <%= link_to "New job", new_job_path, class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="row" , style="margin-left: 30px">
          <div class="col-lg-12">
            <%= search_form_for @q do |f| %>
              <div class="row">
                <div class="col-lg-4">
                  <%= f.label :title_eq, 'Job Title' %>
                  <%= f.select(:title_eq, options_for_select(Job.group(:title).pluck(:title).uniq, (params[:q].nil? ? '' : params[:q][:title_eq])),
                               { :include_blank => 'Select Title' }, { multiple: false, class: "form-control select2", 'data-allow-clear' => 'true', 'data-placeholder' => 'Select Title' }) %>
                </div>
                <div class="col-lg-4">
                  <%= f.label :company_eq, 'Company' %>
                  <%= f.select(:company_eq, options_for_select(Job.group(:company).pluck(:company).uniq, (params[:q].nil? ? '' : params[:q][:company_eq])),
                               { :include_blank => 'Select Company' }, { multiple: false, class: "form-control select2", 'data-allow-clear' => 'true', 'data-placeholder' => 'Select Company' }) %>
                </div>
              </div>
              <br/>
              <div class="row">
                <div class="col-lg-3">
                  <%= f.label :created_at_gteq, 'Created Date/from' %>
                  <%= f.date_field :created_at_gteq, class: 'form-control', value: params[:q].nil? ? '' : params[:q][:created_at_gteq] %>
                </div>
                <div class="col-lg-3">
                  <%= f.label :created_at_lteq, 'Created Date/to' %>
                  <%= f.date_field :created_at_lteq, class: 'form-control', value: params[:q].nil? ? '' : params[:q][:created_at_lteq] %>
                </div>
              </div>
              <br>
              <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <%= f.submit class: 'btn btn-primary btn-sm float-right mr-3' %>
              </div>
            <% end %>
          </div>
        </div>
        <br>

        <div class="row">
          <% if @jobs.present? %>
            <% @jobs.each do |job| %>
              <div class="col-md-4">
                <div class="card job-card">
                  <div class="card-body">
                    <%= link_to 'Apply', new_job_job_application_path(job_id: job.id), class: 'btn btn-primary', style: 'float: right;' %>
                    <h5 class="card-title"><%= job.title %></h5>
                    <p class="card-text"><strong>Company:</strong> <%= job.company %></p>
                    <p class="card-text"><strong>Location:</strong> <%= job.location %></p>
                    <p class="card-text"><strong>Job Type:</strong> <%= job.job_type %></p>
                    <p class="card-text"><strong>Published At:</strong> <%= job.published_at %></p>
                    <p class="card-text"><strong>Expires At:</strong> <%= job.expires_at %></p>
                    <% if can?(:delete, @job) %>
                      <%= button_to "Destroy", @job, method: :delete, class: 'btn btn-danger', style: 'float: right; margin-left: 10px;' %>
                    <% end %>
                    <%= link_to 'View', job_path(job), class: 'btn btn-primary', style: 'float: right; margin-left: 10px;' %>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <h2 style="margin-left: 30px">There are no jobs!</h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
    .form-title {
        color: #fff;
        padding: 1rem;
    }

    .form-title h2 {
        margin: 0;
    }

    .job-card {
        margin-left: 50px;
        margin-right: 50px;
        margin-bottom: 20px;
    }

</style>


<script type="module" src="https://code.jquery.com/jquery-3.3.1.min.js">
    $(document).ready(function () {
        $('.select2').select2();
    });


</script>

app/views/jobs/new.html.erb
<div class="form-title bg-primary text-white py-3">
<h2>New job</h2>
</div>
<br>
<%= render "form", job: @job %>

<style>
    .form-title {
        color: #fff;
        padding: 1rem;
    }

    .form-title h2 {
        margin: 0;
    }

</style>

app/views/jobs/show.html.erb
<br>
<% if @job.present? %>
  <div class="wrapper wrapper-content animated ">
    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <tbody>
            <% Job.column_names.each do |col| %>
              <tr>
                <td><strong><%= col == 'id' ? '#' : col.humanize %></strong></td>
                <td>
                  <%= @job.send(col) %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row">
          <%= if can?(:edit, @job) %>
            <%= link_to "Edit", edit_job_path(@job), class: 'btn btn-primary btn-lg', style: 'margin-left: 10px;' %>
          <% end %>
          <%= link_to "Back", jobs_path, class: 'btn btn-secondary btn-lg', style: 'margin-left: 10px;' %>
          <%= if can?(:delete, @job) %>
            <%= button_to "Destroy", @job, method: :delete, class: 'btn btn-danger btn-lg', style: 'margin-left: 10px;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<br>
<br>
<%= if can?(:delete, @job) %>
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <div class="form-title bg-primary text-white py-2">
            <h5 style="margin-left: 20px">
              Job Application
            </h5>
          </div>
        </div>
        <br>
        <div class="ibox-content">
          <div class="row">
            <div class="col-lg-12">
              <% if @job_applications.present? %>
                <div class="row">
                  <% @job_applications.each do |job_application| %>
                    <div class="col-md-4">
                      <div class="card job-card">
                        <div class="card-body">
                          <% if job_application.not_seen? %>
                            <p class="card-title"> <%= link_to 'Mark as Seen', mark_as_seen_job_job_application_path(job_id: @job.id, id: job_application.id), class: 'btn btn-primary', style: 'float: right;' %></p>
                          <% else %>
                            <p class="card-text" style="float: right;"><span class="seen-icon">✅</span>
                              <strong>Seen</strong>
                          <% end %>
                          <p class="card-text"></p>
                          <p class="card-text"><strong>Name:</strong> <%= job_application.name %></p>
                          <p class="card-text"><strong>Email:</strong> <%= job_application.email %></p>
                          <p class="card-text"><strong>Cover Letter:</strong> <%= job_application.cover_letter %></p>
                          <p class="card-text"><strong>Resume:</strong> <%= job_application.resume %></p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                </div>
              <% else %>
                <h2>There are no job applications yet!</h2>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<style>
    body {
        margin-left: 50px;
        padding-top: 50px;
        margin-bottom: 50px;

    }

    @media (min-width: 768px) {
        body {
            margin-left: 50px;
            margin-bottom: 20px;
            padding-top: 20px;
        }
    }

</style>