config/routes.rb
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'User', at: 'auth'
  root to: 'jobs#index'

  devise_for :users, path: 'auth',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users

  resources :users do
    member do
      get :my_application
    end
  end

  resources :jobs do
    resources :job_applications do
      member do
        get :mark_as_seen
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include DeviseTokenAuth::Concerns::User
  extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable


  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :validatable,
  #        :trackable
  has_many :job_applications

  after_create :assign_default_role

  def assign_default_role
    role = Role.find_by(name: :job_seekers)
    RoleUser.create!(role_id: role.id, user_id: id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @job_applications = JobApplication.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:job).permit(:id, :provider,
                                :uid, :encrypted_password, :reset_password_token,
                                :reset_password_sent_at, :allow_password_change,
                                :remember_created_at, :confirmation_token,
                                :confirmed_at, :confirmation_sent_at,
                                :unconfirmed_email, :name,
                                :nickname, :image, :email,
                                :tokens, :created_at, :updated_at)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def devise_logout_path
    logout_path(resource_name)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<div class="form-title bg-primary text-white py-3">
  <h4 style="margin-top: 10px; margin-left: 10px;"> Job applications for
    <h3 style="margin-top: 10px; margin-left: 10px;" >  <%= @user.email %></h3></h4>
</div>

<% if @job_applications.present? %>
  <div class="row">
    <% @job_applications.each do |job_application| %>
      <div class="col-md-4">
        <div class="card job-card">
          <div class="card-body">
            <% if job_application.not_seen? %>
              <% if can?(:create, job_application) %>
                <p class="card-title"> <%= link_to 'Mark as Seen', mark_as_seen_job_job_application_path(job_id: @job.id, id: job_application.id), class: 'btn btn-primary', style: 'float: right;' %></p>
              <% else %>
                <p class="card-text" style="float: right;"><span class="seen-icon">❌</span> <strong>Seen</strong>
              <% end %>
            <% else %>
              <p class="card-text" style="float: right;"><span class="seen-icon">✅</span> <strong>Seen</strong>
            <% end %>
            <p class="card-text"></p>
            <p class="card-text"><strong>Name:</strong> <%= job_application.name %></p>
            <p class="card-text"><strong>Email:</strong> <%= job_application.email %></p>
            <p class="card-text"><strong>Cover Letter:</strong> <%= job_application.cover_letter %></p>
            <p class="card-text"><strong>Resume:</strong> <%= job_application.resume %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h2 style="margin-left: 20px;">There are no job applications yet!</h2>
<% end %>

<br>
<div class="container-fluid">
  <div class="row">
    <%= link_to "Back to jobs", jobs_path, class: 'btn btn-secondary', style: 'margin-left: 50px;' %>
  </div>
</div>

<style>
    .form-title {
        color: #fff;
        padding: 1rem;
    }

    .form-title h2 {
        margin: 0;
    }

    .job-card {
        margin-left: 50px;
        margin-right: 50px;
        margin-bottom: 20px;
    }

</style>