config/routes.rb
Rails.application.routes.draw do
  # mount_devise_token_auth_for 'User', at: 'auth'
  root to: 'jobs#index'

  devise_for :users, path: 'auth',
                     path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # devise_for :users

  resources :users do
    member do
      get :my_application
    end
  end

  resources :jobs do
    resources :job_applications do
      member do
        get :mark_as_seen
      end
    end
  end
end

app/models/job_application.rb
class JobApplication < ApplicationRecord
  belongs_to :user
  belongs_to :job

  enum status: { seen: 'SEEN', not_seen: 'NOT_SEEN' }
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: %i[show edit update destroy mark_as_seen]
  before_action :set_job, only: %i[index show edit update destroy new create]
  before_action :authenticate_user!

  # GET /job_applications or /job_applications.json
  def index
    @job_applications = if @job.present?
                          JobApplication.where(job_id: @job.id)
                        else
                          JobApplication.all
                        end
  end

  # GET /job_applications/1 or /job_applications/1.json
  def show; end

  # GET /job_applications/new
  def new
    @job_application = JobApplication.new
  end

  # GET /job_applications/1/edit
  def edit; end

  # POST /job_applications or /job_applications.json
  def create
    @job_application = JobApplication.new(job_application_params)

    respond_to do |format|
      if @job_application.save
        if params[:job_application][:resume].present?
          uploaded_file = params[:job_application][:resume]
          filename = "#{@job_application.user.id}-#{@job.title}#{File.extname(uploaded_file.tempfile)}"
          File.open(Rails.root.join('public', filename), 'wb') do |file|
            file.write(uploaded_file.read)
          end
        end
        format.html do
          redirect_to job_job_application_path(@job, @job_application),
                      notice: 'Job application was successfully created.'
        end
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applications/1 or /job_applications/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html do
          redirect_to job_application_url(@job_application), notice: 'Job application was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @job_application }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1 or /job_applications/1.json
  def destroy
    @job_application.destroy

    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: 'Job application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def mark_as_seen
    @job_application.update!(status: :seen)
    UserMailer.application_status(@job_application.user, @job_application.job.title).deliver_now
    redirect_to job_job_applications_path(job_id: params[:job_id]),
                notice: "Job application for #{@job_application.user.email} has been seen"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job_application
    @job_application = JobApplication.find(params[:id])
  end

  def set_job
    @job = Job.find(params[:job_id])
  end

  # Only allow a list of trusted parameters through.
  def job_application_params
    params.require(:job_application).permit(:id, :name, :email, :phone, :resume, :cover_letter,
                                            :status, :user_id, :job_id, :created_at, :updated_at)
  end

  def job_params
    params.require(:job).permit(:id, :title, :description, :company, :location, :job_type,
                                :requirements, :published_at, :expires_at, :created_at, :updated_at)
  end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/views/job_applications/_form.html.erb
<%= form_for [@job, @job_application] do |form| %>
  <% if @job_application.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@job_application.errors.count, "error") %> prohibited this @job_application from being
        saved:</h2>

      <ul>
        <% @job_application.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style="margin: 25px;">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :cover_letter %>
      <%= form.text_area :cover_letter, class: "form-control" %>
      <%= form.hidden_field :job_id, value: @job.id, class: "form-control" %>
      <%= form.hidden_field :user_id, value: current_user.id, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :resume %>
      <%= form.file_field :resume, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.submit class: "btn btn-primary" %>
      <%= link_to "Back", jobs_path, class: 'btn btn-secondary ', style: 'margin-left: 10px;' %>
    </div>
  </div>
<% end %>


<style>
    .job-form {
        max-width: 600px;
        margin: 0 auto;
    }

    .form-group {
        margin-bottom: 1.5rem;
    }

    .form-label {
        font-weight: bold;
        font-size: 1.2rem;
        margin-bottom: 0.5rem;
    }

    .form-control {
        display: block;
        width: 100%;
        padding: 0.5rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .form-control:focus {
        border-color: #80bdff;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

</style>

app/views/job_applications/_job_application.html.erb
<div id="<%= dom_id job_application %>">
</div>

app/views/job_applications/edit.html.erb
<h1>Editing job application</h1>

<%= render "form", job_application: @job_application %>

<br>

<div>
  <%= link_to "Show this job application", @job_application %> |
  <%= link_to "Back to job applications", job_applications_path %>
</div>

app/views/job_applications/index.html.erb
<div class="form-title bg-primary text-white py-3">
  <h4>Job applications for
    <h3> <%= @job.title %></h3></h4>
</div>

<br>
<div class="container-fluid">
  <% if can?(:create, @job_application) %>
    <%= link_to 'New Application', new_job_job_application_path(job_id: @job.id), class: 'btn btn-primary', style: 'float: right;' %>
  <% end %>
</div>
<br>
<br>

<div class="row">
  <% @job_applications.each do |job_application| %>
    <div class="col-md-4">
      <div class="card job-card">
        <div class="card-body">
          <% if job_application.not_seen? %>
            <% if can?(:create, job_application) %>
              <p class="card-title"> <%= link_to 'Mark as Seen', mark_as_seen_job_job_application_path(job_id: @job.id, id: job_application.id), class: 'btn btn-primary', style: 'float: right;' %></p>
            <% else %>
              <p class="card-text" style="float: right;"><span class="seen-icon">❌</span> <strong>Seen</strong>
            <% end %>
          <% else %>
            <p class="card-text" style="float: right;"><span class="seen-icon">✅</span> <strong>Seen</strong>
          <% end %>
          <p class="card-text"></p>
          <p class="card-text"><strong>Name:</strong> <%= job_application.name %></p>
          <p class="card-text"><strong>Email:</strong> <%= job_application.email %></p>
          <p class="card-text"><strong>Cover Letter:</strong> <%= job_application.cover_letter %></p>
          <p class="card-text">
            <strong>Resume:</strong><a href="<%=Rails.root.join('public', "#{job_application.user.id}-#{job_application.job.title}.docx") %>"> Download File</a>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="container-fluid">
  <div class="row">
    <%= link_to "Back to jobs", jobs_path, class: 'btn btn-secondary', style: 'margin-left: 50px;' %>
  </div>
</div>

<style>
    .seen-icon {
        display: inline-block;
        vertical-align: middle;
        margin-left: 5px;
    }

    .form-title {
        color: #fff;
        padding: 1rem;
    }

    .form-title h2 {
        margin: 0;
    }

    .job-card {
        margin-left: 50px;
        margin-right: 50px;
        margin-bottom: 20px;
    }

</style>

app/views/job_applications/new.html.erb
<div class="form-title bg-primary text-white py-3">
  <h2>New job application</h2>
</div>
<br>
<%= render "form", job_application: @job_application %>

<style>
    .form-title {
        color: #fff;
        padding: 1rem;
    }

    .form-title h2 {
        margin: 0;
    }

</style>

app/views/job_applications/show.html.erb
<% if @job_application.present? %>
  <div class="wrapper wrapper-content animated ">
    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <tbody>
            <% JobApplication.column_names.each do |col| %>
              <tr>
                <td><strong><%= col == 'id' ? '#' : col.humanize %></strong></td>
                <td>
                  <%= @job_application.send(col) %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row">
          <%= link_to "Back to job applications", job_job_applications_path(@job), class: 'btn btn-secondary btn-lg', style: 'margin-left: 10px;' %>
         </div>
      </div>
    </div>
  </div>
<% end %>

<style>
    body {
        margin-left: 50px;
        padding-top: 20px;
        margin-bottom: 20px;

    }

    @media (min-width: 768px) {
        body {
            margin-left: 50px;
            margin-bottom: 20px;
            padding-top: 20px;
        }
    }

</style>